name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install pnpm
      - run: npm install -g pnpm

      # Install dependencies using pnpm
      - run: pnpm install --frozen-lockfile

      # Run tests
      - run: pnpm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Install pnpm
      - run: npm install -g pnpm

      # Install dependencies
      - run: pnpm install --frozen-lockfile

      # Build your project
      - run: pnpm run build

      # Publish to npm
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
